# Site settings
title: FESC2015 by Adab1ts
email: info@adabits.org
description: Website de demostració per a la FESC 2015, 23-25 d'octubre.
baseurl: ""
url: "http://fesc2015.adabits.org"


# Paths
# sass:
#   sass_dir: assets/styles

# Handling Reading
exclude: ['assets/sass']

# Filtering Content
show_drafts: false
future:      false

# Plugins
# gems:
#   - jekyll-redirect-from
#   - jekyll-sitemap
gems:
- jekyll-feed
- jekyll-sitemap

# Conversion
markdown:    kramdown
highlighter: pygments

# Markdown Processors
kramdown:
  input: GFM
