# Site settings
baseurl: ""
url: "https://fesc2015.adabits.org"
lang: 'ca'
timezone: Europe/Madrid

# Site info
title: FESC2015 by Adab1ts
description: Website de demostració per a la FESC 2015, 23-25 d'octubre.
email: info@adabits.org

# Paths
# sass:
#   sass_dir: assets/styles

# Handling Reading
exclude: ['assets/sass']
encoding: "utf-8"
markdown_ext: "md"

# Filtering Content
show_drafts: false
future:      false

# Plugins
# gems:
#   - jekyll-redirect-from
#   - jekyll-sitemap
gems:
  - jekyll-feed

# Conversion
markdown:    kramdown
highlighter: rouge

# Outputting
permalink: /guestbook/:year/:month/:day/:title/

# Markdown Processors
kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      image_path: /images/postcards/sample.jpg
